version: '3'
services:
  anaconda:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: /bin/bash -c "source activate base && jupyter notebook --notebook-dir=/app --ip='*' --port=8888 --no-browser --allow-root"